### ISSUE TITLE
How to change the Loading / Error component ?

### ISSUE THREAD

**Issue by zvictor** [sammkj/react-komposer-plus#1]
It seems that `composeWithRedux` does only accept one argument, blocking the access to the rest of the `compose(fn, L1, E1, options = { pure: true })` signature.

Wouldn't something like the following work better?

``` js
export default function composeWithRedux(fn, L1, E1, options) {
  return compose(composeReduxBase.bind(null, fn),  L1, E1, options);
}
```

**Comment by zvictor** [comment]
Thank you @sammkj! It works for me and I can see both loading (on first render) and error components working in my project, but I have a question.

How am I supposed to render the loading screen again? With `react-komposer` I had to return `null` as my data, and then the loading component would be rendered again. The same does not work with `react-komposer-plus`.

``` jsx
const mapStateToProps = ({ myData, requests }) => {
  if (myData.error) {
    throw myData.error;
  }

  if (requests.pending) {
    return null;
  }

  return myData;
};
```

Is this the way I am supposed to define my `mapStateToProps`?

**Comment by kokjinsam** [comment]
@zvictor , `composeWithRedux` is just a state mapper like `connect` in `react-redux`. The loading component that you pass into `composeWithRedux`  will only be displayed when we're getting the state from the store. For most cases, the loading component won't be displayed as getting state from the store is very fast. Unless you're using something like Apollo that uses Redux as a store for domain state.

From your example, it seems like you're trying to display a loading screen when the request is pending, correct? What I would do is:

```
const mapStateToProps = ({ myData, requests }) => ({
  pending: requests.pending,
  mydata,
});
```

Then in my component,

```
const compA = ({
  pending,
  mydata,
}) => (
  {pending ? <div>request pending</div> : null}
  <div>{mydata}</div>
)
```

And finally, create an action that updates the `requests.pending` state in the store.

I hope that answers your question. Let me know if you have more questions!
